"""Creación de tablas para temas, ejercicios y respuestas

Revision ID: 1728521948dc
Revises: 41aa789df91c
Create Date: 2025-05-10 19:44:43.575843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1728521948dc'
down_revision: Union[str, None] = '41aa789df91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Crear la tabla de 'temas'
    op.create_table(
        'temas',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('nombre', sa.String(length=255), nullable=False, unique=True),
        sa.Column('descripcion', sa.Text(), nullable=True)
    )

    # Crear la tabla de 'ejercicios'
    op.create_table(
        'ejercicios',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('enunciado', sa.Text(), nullable=False),
        sa.Column('tipo', sa.String(length=50), nullable=False),  # suma, resta, multiplicación, etc.
        sa.Column('dificultad', sa.String(length=50), nullable=False),  # fácil, intermedio, difícil
        sa.Column('tema_id', sa.Integer(), sa.ForeignKey('temas.id', ondelete='CASCADE'), nullable=False)
    )

    # Crear la tabla de 'respuestas_usuarios'
    op.create_table(
        'respuestas_usuarios',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('respuesta', sa.Text(), nullable=False),
        sa.Column('ejercicio_id', sa.Integer(), sa.ForeignKey('ejercicios.id', ondelete='CASCADE'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('correcto', sa.Boolean(), nullable=False)  # Indica si la respuesta es correcta o no
    )

    # Crear relaciones en las tablas
    op.create_foreign_key(
        'fk_respuestas_usuarios_user',
        'respuestas_usuarios', 'users',
        ['user_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_respuestas_usuarios_ejercicio',
        'respuestas_usuarios', 'ejercicios',
        ['ejercicio_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_ejercicios_tema',
        'ejercicios', 'temas',
        ['tema_id'], ['id'], ondelete='CASCADE'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subjects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='user_subjects_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subjects_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', name='uq_user_subject')
    )
    op.create_table('users_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_providers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='users_providers_pkey'),
    sa.UniqueConstraint('provider_user_id', 'provider', name='uq_provider_user_id_provider')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey'),
    sa.UniqueConstraint('token', name='refresh_tokens_token_key')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.CheckConstraint("password::text ~* '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z0-9]).{8,}$'::text", name='chk_password_complexity'),
    sa.CheckConstraint('length(username::text) >= 3', name='chk_name_min_length'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('subjects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey'),
    sa.UniqueConstraint('name', name='subjects_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    sa.UniqueConstraint('title', name='courses_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('course_subjects',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_subjects_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='course_subjects_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'subject_id', name='uq_course_subject')
    )
    op.create_table('user_courses',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='user_courses_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_courses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='uq_user_course')
    )
    # ### end Alembic commands ###
