"""add courses and subjects

Revision ID: a7a8d2e751ad
Revises: ac43e51fb2a4
Create Date: 2025-04-17 18:29:36.940287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a8d2e751ad'
down_revision: Union[str, None] = 'ac43e51fb2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This migration's original content conflicted with ac43e51fb2a4.
    # Adjusted to be a no-op.
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # This migration's original content conflicted with ac43e51fb2a4.
    # Adjusted to be a no-op.
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
