"""baseline existing schema

Revision ID: ac43e51fb2a4
Revises: d6dedfa39a3d
Create Date: 2025-04-17 18:29:23.671516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac43e51fb2a4'
down_revision: Union[str, None] = 'd6dedfa39a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_subjects',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'subject_id'),
    sa.UniqueConstraint('course_id', 'subject_id', name='uq_course_subject')
    )
    op.create_unique_constraint('uq_user_course', 'user_courses', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_course', 'user_courses', type_='unique')
    op.drop_table('course_subjects')
    # ### end Alembic commands ###
