"""drop user_subjects table

Revision ID: c2d3e4f5a6b7
Revises: b1c2d3e4f5a6
Create Date: 2025-05-11 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d3e4f5a6b7'
down_revision: Union[str, None] = 'b1c2d3e4f5a6' # La migración que creó user_enrollments
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subjects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subjects",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_user_subjects_user_id", ondelete="CASCADE" # Nombre de FK puede variar si era auto-generado
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["subjects.id"], name="fk_user_subjects_subject_id", ondelete="CASCADE" # Nombre de FK puede variar
        ),
        sa.PrimaryKeyConstraint("user_id", "subject_id", name="pk_user_subjects"), # Nombre de PK puede variar
        sa.UniqueConstraint("user_id", "subject_id", name="uq_user_subject"), # Este nombre sí estaba definido
    )
    # ### end Alembic commands ###
