"""add courses and subjects

Revision ID: d6dedfa39a3d
Revises: dfb73c4f1837
Create Date: 2025-04-17 18:27:11.855622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6dedfa39a3d'
down_revision: Union[str, None] = 'dfb73c4f1837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_courses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course')
    )
    op.add_column('courses', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_constraint('courses_name_key', 'courses', type_='unique')
    op.create_unique_constraint(None, 'courses', ['title'])
    op.drop_column('courses', 'name')
    op.add_column('subjects', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'subjects', ['name'])
    op.drop_constraint('subjects_course_id_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_course_id_fkey', 'subjects', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'subjects', type_='unique')
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('subjects', 'description')
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='unique')
    op.create_unique_constraint('courses_name_key', 'courses', ['name'])
    op.drop_column('courses', 'title')
    op.drop_table('user_courses')
    # ### end Alembic commands ###
