"""Migración inicial

Revision ID: dfb73c4f1837
Revises: 
Create Date: 2025-03-28 10:48:16.658769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfb73c4f1837'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_providers_provider_user_id_provider_key', 'users_providers', type_='unique')
    op.create_unique_constraint('uq_provider_user_id_provider', 'users_providers', ['provider_user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_user_id_provider', 'users_providers', type_='unique')
    op.create_unique_constraint('users_providers_provider_user_id_provider_key', 'users_providers', ['provider_user_id', 'provider'])
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
