"""Añade timezone=True a expires_at

Revision ID: f313f70c3072
Revises: a7a8d2e751ad
Create Date: 2025-05-05 22:00:57.318686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f313f70c3072'
down_revision: Union[str, None] = 'a7a8d2e751ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'refresh_tokens',
        'expires_at',
        existing_type=sa.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'refresh_tokens',
        'expires_at',
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(timezone=False), # Revert to TIMESTAMP without timezone
        nullable=False
    )
    # ### end Alembic commands ###
